# Generated by Django 4.2.4 on 2023-08-17 05:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_client"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_name",
        ),
    ]
