# Generated by Django 4.2.4 on 2023-08-17 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_remove_user_first_name_remove_user_last_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuperUser",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("first_name", models.CharField(default="", max_length=256)),
                ("last_name", models.CharField(default="", max_length=256)),
            ],
            options={
                "verbose_name_plural": "Super User",
            },
            bases=("account.user",),
        ),
    ]
