# Generated by Django 4.2.4 on 2023-08-17 06:15

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0005_superuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="superuser",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region="IN"
            ),
        ),
        migrations.DeleteModel(
            name="Client",
        ),
    ]
