# Generated by Django 4.2.4 on 2023-08-17 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0006_superuser_phone_number_delete_client"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(default="", max_length=256, unique=True),
                ),
            ],
            options={
                "verbose_name_plural": "Client",
            },
            bases=("account.user",),
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("username", models.CharField(default="", max_length=256, unique=True)),
                ("first_name", models.CharField(default="", max_length=256)),
                ("last_name", models.CharField(default="", max_length=256)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region="IN"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Admin",
            },
            bases=("account.user",),
        ),
        migrations.CreateModel(
            name="FieldExecutive",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("username", models.CharField(default="", max_length=256, unique=True)),
                ("first_name", models.CharField(default="", max_length=256)),
                ("last_name", models.CharField(default="", max_length=256)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region="IN"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Field Executive",
            },
            bases=("account.user",),
        ),
        migrations.CreateModel(
            name="RiskCoordinator",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("username", models.CharField(default="", max_length=256, unique=True)),
                ("first_name", models.CharField(default="", max_length=256)),
                ("last_name", models.CharField(default="", max_length=256)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region="IN"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Risk Co-Ordinator",
            },
            bases=("account.user",),
        ),
        migrations.CreateModel(
            name="SuperAdmin",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("username", models.CharField(default="", max_length=256, unique=True)),
                ("first_name", models.CharField(default="", max_length=256)),
                ("last_name", models.CharField(default="", max_length=256)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region="IN"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Super Admin",
            },
            bases=("account.user",),
        ),
        migrations.DeleteModel(
            name="SuperUser",
        ),
    ]
