# Generated by Django 4.2.4 on 2023-08-21 09:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "issuance_type",
                    models.CharField(
                        choices=[
                            ("Pre Issuance", "Pre Issuance"),
                            ("Post Issuance", "Post Issuance"),
                            ("Not Applicable", "Not Applicable"),
                        ],
                        max_length=64,
                        verbose_name="Issuance Type",
                    ),
                ),
                (
                    "type_of_check",
                    models.CharField(
                        choices=[
                            ("Profile Check", "Profile Check"),
                            ("Discreet Check", "Discreet Check"),
                            ("Mystery Shopping", "Mystery Shopping"),
                            ("Doctor Seeding", "Doctor Seeding"),
                            ("Account Verification", "Account Verification"),
                            ("Document Verification", "Document Verification"),
                            ("Number Verification", "Number Verification"),
                            ("Mystery Calling", "Mystery Calling"),
                        ],
                        max_length=64,
                        verbose_name="Type Of Check",
                    ),
                ),
                (
                    "type_of_visit",
                    models.CharField(
                        choices=[
                            ("Direct", "Direct"),
                            ("Appointment", "Appointment"),
                            ("Discreet Only", "Discreet Only"),
                        ],
                        max_length=64,
                        verbose_name="Type Of Visit",
                    ),
                ),
                (
                    "appointment_status",
                    models.TextField(
                        blank=True,
                        default="",
                        null=True,
                        verbose_name="Appointment Status",
                    ),
                ),
                (
                    "refered_by",
                    models.CharField(max_length=255, verbose_name="Refered By"),
                ),
                ("in_date", models.DateField(verbose_name="In Date")),
                ("in_time", models.TimeField(verbose_name="In Time")),
                ("consider_date", models.DateField(verbose_name="Consider Date")),
                ("due_date", models.DateField(verbose_name="Due Date")),
                ("out_date", models.DateField(verbose_name="Out Date")),
                (
                    "delayed_reason",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="Delayed Reason"
                    ),
                ),
                (
                    "turn_around_time",
                    models.CharField(
                        choices=[("WT", "Wt"), ("NA", "Na"), ("OT", "Ot")],
                        max_length=64,
                        verbose_name="Turn Around Time",
                    ),
                ),
                (
                    "turn_around_time_in_days",
                    models.CharField(max_length=64, verbose_name="TAT In Days"),
                ),
                (
                    "mail_subject_line",
                    models.CharField(max_length=256, verbose_name="Mail Subject Line"),
                ),
                (
                    "policy_number",
                    models.CharField(
                        max_length=256, unique=True, verbose_name="Policy Number"
                    ),
                ),
                (
                    "application_number",
                    models.CharField(
                        max_length=256, unique=True, verbose_name="Application Number"
                    ),
                ),
                ("urn", models.CharField(max_length=64, verbose_name="URN")),
                (
                    "customer_name",
                    models.CharField(max_length=256, verbose_name="Customer Name"),
                ),
                (
                    "father_name",
                    models.CharField(max_length=256, verbose_name="father Name"),
                ),
                ("address", models.TextField(verbose_name="Address")),
                ("city", models.CharField(max_length=256, verbose_name="City")),
                ("pincode", models.CharField(max_length=64, verbose_name="Pincode")),
                ("state", models.CharField(max_length=64, verbose_name="State")),
                (
                    "contact_number",
                    models.CharField(max_length=64, verbose_name="Contact Number"),
                ),
                (
                    "scope_of_investigation",
                    models.TextField(verbose_name="Scope of Investigation"),
                ),
                (
                    "investigatior_name",
                    models.CharField(max_length=64, verbose_name="Investigatior Name"),
                ),
                (
                    "remark",
                    models.TextField(
                        blank=True,
                        default="",
                        null=True,
                        verbose_name="Remark - As per Rece. Findings",
                    ),
                ),
                (
                    "case_status",
                    models.CharField(
                        choices=[
                            ("Positive", "Positive"),
                            ("Negative", "Negative"),
                            ("Highly Negative", "Highly Negative"),
                            ("Suspicious", "Suspicious"),
                        ],
                        max_length=64,
                        verbose_name="Case Status",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        default="",
                        null=True,
                        verbose_name="If Highly Negative/ Negative/ Suspicious - Reason",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_cases",
                        to="account.client",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Case",
            },
        ),
    ]
