# Generated by Django 4.2.4 on 2023-08-21 09:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("account", "0001_initial"),
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskForRiskCoordinator",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("New Case", "Newcase"),
                            ("Assigned", "Assigned"),
                            ("Re-Assigned", "Reassigned"),
                            ("Drop Case", "Dropcase"),
                            ("Done", "Done"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cases.case"
                    ),
                ),
                (
                    "risk_coordinator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_coordinator_tasks",
                        to="account.riskcoordinator",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_tasks",
                        to="account.superadminandadmin",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Task For Risk Co-Ordinator",
            },
        ),
        migrations.CreateModel(
            name="TaskForFieldExecutive",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "field_executive",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_executive_tasks",
                        to="account.fieldexecutive",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_coordinator_assigned_task",
                        to="tasks.taskforriskcoordinator",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Task For Field Executive",
            },
        ),
    ]
